name: unicef1
recipe: drupal9
config:
  webroot: web
  php: "7.3"
  drush: ^9.5
  composer_version: '2.0.7'
  xdebug: true
  conf:
    php: .vscode/php.ini
proxy:
  web:
    - unicef1.danielmm.com.br
